### Recuperar todas las peliculas 
GET http://localhost:1235/movies

### Recupera peliculas por ID 
GET http://localhost:1235/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Recupera peliculas por genero , se usa un queryString
GET http://localhost:1235/movies?genre=Action


### Crear pelicula con POST
POST http://localhost:1235/movies
Content-Type: application/json

{
    
    "title": "El taller del maestro",
    "year": 2022
    
  }

###Actulizar una pelicula pero una parte nada mas
PATCH http://localhost:1235/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf
Content-Type: application/json

{
    "year": 2022
}