# ###para obterner un pokemon
# GET http://localhost:1234/pokemon/ditto

# ### para crear un pokemon 

# POST http://localhost:1234/pokemon
# Content-Type: application/json
# {
#     "name": "ditto",
#     "type": "normal",
#     "moves": [
#         "transform"
#     ]
# }

### Recuperar información del pokemon ditto
GET http://localhost:1234/pokemon/ditto

### Para crear un Pokemon
POST http://localhost:1234/pokemon
Content-Type: application/json

{
  "name": "ditto",
  "type": "normal",
  "moves": [
      "transform"
  ]
}